In [1]:
from utils import get_path, set_temporary_np_seed_as
import numpy as np

def _sample_from_dataset(dataset: list, rate: float, use_rating: bool=False, seed: int=0):
    if not use_rating:
        item_train, item_valid, item_test, usernum, itemnum = dataset[:5]
    else:
        item_train, item_valid, item_test, usernum, itemnum, rating_train, rating_valid, rating_test = dataset
    
    n_sampled_user = int(usernum * rate)
    with set_temporary_np_seed_as(seed):
        selected_users = list(np.random.choice(range(usernum), n_sampled_user, replace=False))
    
    def _select_from(a: list, indices: list):
        tmp_array = np.array(a, dtype=object)
        selected_list = list(tmp_array[indices])
        del tmp_array
        return selected_list
    
    new_item_train = _select_from(item_train, selected_users)
    new_item_valid = _select_from(item_valid, selected_users)
    new_item_test = _select_from(item_test, selected_users)

    if not use_rating:
        return [new_item_train, new_item_valid, new_item_test, n_sampled_user, itemnum]
    else:
        new_rating_train = _select_from(rating_train, selected_users)
        new_rating_valid = _select_from(rating_valid, selected_users)
        new_rating_test = _select_from(rating_test, selected_users)

        return [new_item_train, new_item_valid, new_item_test, n_sampled_user, itemnum, new_rating_train, new_rating_valid, new_rating_test]

In [2]:
import pickle

In [6]:
sample_path = get_path("Data/Cache/sampled_lastfm_small-5-5-rate-0.8-seed-2000.pkl")

sampled_dataset = pickle.load(sample_path.open('rb'))

dataset = sampled_dataset[1]

In [9]:
item_train, item_valid, item_test, usernum, itemnum, rating_train, rating_valid, rating_test = dataset

In [12]:
list(item_test)

[array([1665], dtype=object),
 array([292], dtype=object),
 array([1005], dtype=object),
 array([3301], dtype=object),
 array([3405], dtype=object),
 array([2820], dtype=object),
 array([1158], dtype=object),
 array([1522], dtype=object),
 array([3209], dtype=object),
 array([1227], dtype=object),
 array([520], dtype=object),
 array([3011], dtype=object),
 array([530], dtype=object),
 array([809], dtype=object),
 array([2395], dtype=object),
 array([2945], dtype=object),
 array([1871], dtype=object),
 array([3355], dtype=object),
 array([2432], dtype=object),
 array([2291], dtype=object),
 array([291], dtype=object),
 array([1116], dtype=object),
 array([3495], dtype=object),
 array([2639], dtype=object),
 array([292], dtype=object),
 array([3115], dtype=object),
 array([2391], dtype=object),
 array([287], dtype=object),
 array([2295], dtype=object),
 array([3095], dtype=object),
 array([3040], dtype=object),
 array([108], dtype=object),
 array([3219], dtype=object),
 array([3312], dty

In [13]:
full_dataset_path = get_path("Data/Cache/lastfm_small-5-5.pkl")

full_dataset = pickle.load(full_dataset_path.open('rb'))

dataset = full_dataset[1]

In [15]:
item_train, item_valid, item_test, usernum, itemnum, rating_train, rating_valid, rating_test = dataset

In [17]:
def select_from(a: list, indices: list):
    tmp_array = np.array(a, dtype=object)
    selected_list = list(tmp_array[indices])
    del tmp_array
    return selected_list

In [18]:
n_sampled_user = int(usernum * 0.1)
with set_temporary_np_seed_as(0):
    selected_users = list(np.random.choice(range(usernum), n_sampled_user, replace=False))

In [51]:
a = [[1, 2], [2], [3]]

In [52]:
b = np.array(a, dtype=list)

In [53]:
np.ndarray.tolist(b[[0, 1]])

[[1, 2], [2]]